<div class="container">

<h2><strong>Términos y Condiciones de Contratación </strong></h2>
<h3><strong>En general:</strong></h3>
<p>Finguer no se hace responsable de los accesorios extraíbles que se encuentran en el interior del vehículo, si su existen- cia no ha sido comunicada a nuestro personal en el momento de la recepción del vehículo, verificada la existencia y el funcionamiento por nuestro personal y anotada en el contrato antes de la aceptación de éste por parte del cliente. Tal y como dispone el art.3.3 de la Ley 40/2002, de 14 de noviembre, reguladora del contrato de aparcamiento de vehículos, Finguer podrá establecer precios distintos o complementarios para la guarda y vigilancia de los efectos cuya custodia acepte.</p>
<p>En el supuesto de que el Servicio de Aparcamiento contratado y/o los Servicios complementarios (ej. Lavado) impli- quen la entrega de llaves al personal de Finguer, la empresa se reserva el derecho a mover el vehículo si causas organi- zativas así lo aconsejan.</p>

<p>Para que Finguer proceda a valorar su responsabilidad, en el supuesto de que el Servicio de Aparcamiento contratado y/o los Servicios complementarios (ej. Lavado) impliquen la entrega de llaves al personal de Finguer, la empresa se re- serva el derecho a mover el vehículo si causas organizativas así lo aconsejan. En el caso de que vehículo presente algún daño que pudiera haber sido ocasionado durante la custodia del mismo, el cliente deberá comunicar a los empleados de Finguer la existencia de dichos desperfectos en el momento de la recogida de su vehículo, debiendo dicha queja ser recogida en la correspondiente acta; en el caso de no efectuar comunicación alguna antes de abandonar las instala- ciones de Finguer se entenderá como conformidad táctica por parte del cliente con el estado del vehículo, e implicará la exoneración de cualquier responsabilidad de Finguer respecto de cualquier daño que con posterioridad pueda ser alegado por parte del cliente. En el supuesto de que los daños se deban a robo-expoliación será necesario tramitar la correspondiente denuncia ante las Fuerzas y Cuerpos de Seguridad competentes.</p>
<p>Website Finguer®</p>

<h3><strong>1.Titularidad y objeto de la Plataforma Web</strong></h3>

<p>1.1 El sitio Web www.finguer.com (en adelante la “Web” o “la plataforma”) es una plataforma informática propiedad de Aparca &amp; Go S.L (en adelante “La Empresa” o “Finguer”), Sociedad legalmente constituida bajo la legislación espa- ñola con domicilio en Carrer de Marisol 3 &#8211; 08860 Castelldefels, CIF B-65548919 e inscrita en el Registro Mercantil de Barcelona bajo el tomo 42.518, folio 0024, y hoja número B408388.</p>

<p>1.2 Nuestra página Web ha sido diseñada con la finalidad de ofrecer a nuestros usuarios información detallada sobre nuestros servicios de aparcamiento y nuestras aplicaciones. A través de Finguer podrás localizar, reservar y acceder a nuestros servicios de parking tanto en los principales aeropuertos y estaciones de tren como en nuestra red de parkings públicos localizados en las principales ciudades españolas y, asimismo, gestionar a través de la plataforma Web tu cuenta de usuario, los servicios solicitados, tus reservas y tu facturación.</p>

<h3><strong>2. Definiciones</strong></h3>

<p>2.1 Plataforma: consiste en la página Web www.finguer.com incluyendo determinadas áreas no públicas accesibles únicamente a usuarios autorizados.</p>

<p>2.2 Contenidos: se refiere a todos los elementos que conforman el sitio Web, incluyendo a titulo enunciativo más no limitativo; textos, imágenes, software, videos, diseños y cualquiera de sus modificaciones.</p>
<p>2.3 Agencias: se refiere a las agencias de viajes que utilizan como valor añadido a su carta de servicios los servicios de Finguer y, en virtud de dicha colaboración, acceden en calidad de usuarios a nuestra Plataforma. Salvo que se indique expresamente lo contrario, serán también aplicables a las Agencias aquellas disposiciones de los presentes Términos y Condiciones aplicables a los usuarios finales.</p>

<p>2.4 Propietarios: son las personas físicas o entidades propietarias de un parking o plazas de parking y que pertenecen a la red de colaboradores autorizados de Finguer.</p>

<p>2.5 Usuarios/Usuario: es el usuario final de los servicios de parking de Finguer que accede a la plataforma y/o a las aplicaciones de Finguer en calidad de usuario registrado a efecto de gestionar personalmente los servicios solicitados, sus reservas y su facturación. Recibirá también la calificación de usuario final de los servicios de parking de Finguer aquellas personas para las que una Agencia (en los términos del punto 2.3 de esta sección) haya reservado los servicios de Finguer en cualquiera de las modalidades ofrecidas.</p>

<h3><strong>3. Aceptación de los Términos y Condiciones</strong></h3>

<p>3.1. El acceso a y uso de nuestra Plataforma así como la información, servicios y contenido están sujetos a la legisla- ción y normativa reguladora aplicable así como a las disposiciones establecidas en los presentes Términos y Condicio- nes de Uso.</p>
<p>3.2. El Usuario reconoce y acepta haber leído y comprendido los Términos y Condiciones de Contratación de la Plataforma cuyo contenido constituye la totalidad del acuerdo entre el Usuario y Finguer. Al registrarse y utilizar los servicios de nuestra Web, el Usuario expresamente reconoce y acepta obligarse por los Términos y Condiciones de Contración así como por la Política de Privacidad de la plataforma y otras políticas corporativas de Finguer que sean de aplicación. Asimismo, el Usuario reconoce y acepta que los servicios y contenidos ofrecidos a través de la Plataforma no infringen ni deberán ser utilizados para infringir la normativa y/o regulaciones vigentes aplicables.</p>

<p>3.3. Finguer se reserva el derecho de modificar los términos y condiciones de Uso de la Plataforma sin mediar notifi- cación específica al Usuario. En este sentido es importante que el Usuario consulte los Términos y Condiciones de Uso regularmente.</p>

<h3><strong>4. Registro de Usuarios Web</strong></h3>

<p>4.1. La plataforma Web de Finguer está destinada a usuarios mayores de edad. Al registrarse en nuestra Web el Usuario garantiza que cumple con este requisito.</p>

<p>4.2. Para poder utilizar los servicios de nuestra plataforma, es necesario que te registres como Usuario facilitando tus datos personales. En el caso de las Agencias te requeriremos rellenar un formulario de registro con información concreta sobre el grupo de Agencias al que perteneces y tu información de contacto. Para todos los usuarios será nece- sario crear un nombre de usuario y contraseña de acceso.</p>

<p>4.3. El Usuario reconoce y acepta que Finguer podrá utilizar sus credenciales de acceso con la exclusiva finalidad de validar los procesos de identificación y autenticación a nuestra Plataforma. Por tanto, es el Usuario y no Finguer el responsable de utilizar correctamente y proteger su contraseña de acceso. El Usuario deberá notificar a Finguer de cualquier incidente o uso no autorizado que pudiera afectar a su cuenta de usuario.</p>

<p>4.4. El Usuario reconoce y acepta que Finguer podrá suspender o cancelar el acceso por parte del Usuario a nuestra Web, con o sin notificación previa, en el caso de que existan sospechas razonables, a juicio de Finguer, del uso indebi- do, por parte del Usuario, de los servicios y funcionalidades de nuestra Plataforma y, asimismo, cuando exista incumpli- miento de cualquiera de las disposiciones contenidas en los presentes Términos y Condiciones de Uso.</p>


<h3><strong>5. Uso de los Servicios Web</strong></h3>

<p>5.1. Los servicios de Finguer a través de nuestra Plataforma Web permiten gestionar las reservas de nuestras plazas de parking, ya sea para necesidades de larga duración. Con la finalidad de facilitar la gestión de los servicios que con- trates con Finguer, tanto los servicios solicitados, como las reservas y la facturación estarán disponibles accediendo al área privada de Usuario de la Plataforma.</p>

<p>5.2. En el caso de Usuarios finales, es posible realizar reservas sin registrarse en la Plataforma. No obstante, será imprescindible que nos facilites nombre y apellidos del conductor del vehículo, matrícula del vehículo y teléfono. Todas las reservas realizadas a través de cualquier medio establecido por Finguer son de carácter gratuito. Las reservas para parkings viajeros se mantendrán hasta 3 horas adicionales a partir de la hora de entrada comunicada por el usuario en el momento de la reserva. En el caso de que el Usuario por cualquier circunstancia no acceda al parking dentro de los límites fijados por Finguer el Usuario perderá todo derecho de acceso al servicio sin ningún tipo de responsabilidad para Finguer. En momentos determinados, por causas operacionales, puede ser necesario dejar la llave del vehículo para poder aparcar en nuestras instalaciones.</p>
<p>5.3. La tarifa del estacionamiento con reserva de plaza se calculará por periodos de 24 horas y/o fracción, a contar des- de la fecha y hora de acceso al aparcamiento, hasta la salida del vehículo del mismo, estableciéndose un tiempo de cor- tesía de 60 minutos tras el último período de 24 horas. El importe mínimo de pago será el correspondiente a la estancia mínima según las condiciones del producto/aparcamiento/aeropuerto, y el tiempo de estancia se contabilizará por días completos (24 horas) y/o fracción. El importe de las tarifas de estacionamiento con reserva de plaza y los tiempos de cortesía se establecerán en cada uno de los estacionamientos de Finguer.</p>

<p>5.4. Una vez registrado el Usuario y finalizada la reserva, el acceso a los parkings de Finguer se habilita a través del código QR que el Usuario es responsable de escanear correctamente para acceder al parking correspondiente. A efec- to de activar correctamente los servicios, el Usuario debe seguir las instrucciones e información concreta que Finguer le traslade en la confirmación de reserva.</p>

<p>5.5. El Usuario reconoce y acepta, en cuanto a los servicios ofrecidos a través de las plazas de aparcamiento pro- piedad de la red de colaboradores de Finguer (en adelante, “el Propietario”), que tanto las tarifas como los horarios<br />
de apertura y cierre así como cualquier restricción relacionada con el uso del parking es información directamente facilitada por el Propietario del parking y no por Finguer. En ese sentido, cualquier cambio o modificación en dichas tarifas, horarios y restricciones está fuera del control de Finguer. En consecuencia, el Usuario reconoce y acepta que es el Propietario del parking el principal responsable de la información facilitada y no Finguer, con lo que Finguer declina cualquier responsabilidad en relación a cualquier incidencia o situación que pudiera afectar al Usuario con motivo de dicha información.</p>

<p>5.6. Asimismo, el Usuario reconoce y acepta que las normas establecidas por el parking seleccionado le serán de aplicación y que el uso de los servicios de nuestra Web, no le exime de cumplir con dichas normas y, por tanto, se obliga a cumplirlas.</p>

<p>5.7. Las tarifas de las categorías de suscripción a los servicios de Finguer, incluyendo los servicios adicionales, pro- grama de puntos, los métodos de pago y la información de facturación se mostrarán oportunamente durante la reserva de los servicios realizada por el Usuario desde la aplicación, no obstante, Finguer podrá remitir al usuario notificaciones asociadas al servicio contratado o a posibles servicios adicionales que puedan ser de su interés. Sin perjuicio de las cantidades que el Usuario deba pagar a Finguer por la utilización de los servicios, el Usuario será responsable de asu- mir todos los cargos asociados con el uso de su dispositivo móvil. El Usuario reconoce y acepta que algunos servicios promocionales ofrecidos por Finguer pueden estar sujetos a caducidad y a otras posibles restricciones que pueden no ser controladas de forma directa por Finguer, con lo que, Finguer trasladará al Usuario toda la información relativa a los servicios adicionales y/o promocionales. En ese sentido, Finguer no será responsable de cualquier incidencia, impo- sibilidad de hacer valer los beneficios promocionales o cualquier otra circunstancia que impida al Usuario disfrutar de dichos beneficios.</p>

<p>5.7. De forma general Finguer mostrará la información relativa a las tarifas del servicio bajo el formato “precio/hora”, informándose expresamente al Usuario que la facturación se realizará por minutos. A tales efectos, el Usuario autoriza a Finguer a cargar la tarifa aplicable en función de la utilización de los servicios y a procesar la transacción correspon- diente de acuerdo al medio de pago seleccionado por el Usuario.</p>

<p>5.8. En ningún caso, Finguer reembolsará las cantidades efectivamente pagadas por el Usuario por la utilización de los servicios de parking.</p>

<p>5.9. La falta de pago a Finguer de las tarifas correspondientes a los servicios utilizados tendrá como consecuencia, a discreción de Finguer, la suspensión o cancelación de la cuenta de usuario encontrándose Finguer facultada para contratar los servicios de un tercero con el objeto de recuperar el pago de las cantidades adeudadas. En este sentido, el Usuario acepta reembolsar a Finguer la totalidad de los gastos y costas derivados de la reclamación de lo adeudado, incluyendo honorarios de abogados, procuradores y tasas de oficiales de los Juzgados y Tribunales.</p>

<h3><strong>6. Exclusiones de Responsabilidad</strong></h3>

<p>6.1. En razón a las situaciones imprevisibles que caracterizan a los entornos tecnológicos y a Internet, Finguer se reserva el derecho de suspender temporalmente los servicios de la Plataforma, ya sea por razones de carácter técnico, por motivos de seguridad o por mantenimiento. La suspensión de los servicios no confiere derecho alguno de com- pensación al Usuario, aunque Finguer pondrá sus mejores esfuerzos para limitar en la medida de lo posible cualquier suspensión o interrupción de los servicios. Asimismo, Finguer se reserva el derecho de implementar y realizar cambios y/o actualizaciones de la Web en cualquier momento, con o sin notificación previa. En cualquier caso, El Usuario reco- noce y acepta que Finguer podrá realizar determinadas acciones para impedir el acceso del Usuario a la Plataforma en determinados momentos por períodos limitados. En este sentido, el Usuario acepta que Finguer no será responsable, como resultado de dichas acciones, de la eliminación o fallo en la puesta a disposición de ciertos servicios o funcionali- dades de la plataforma Web.</p>

<p>6.2. Finguer no representa ni garantiza la obtención de determinados resultados tras la utilización de los servicios de la Plataforma. En consecuencia, bajo ninguna circunstancia Finguer, sus representantes, directores, empleados serán responsables por cualquier daño incidental , fortuito, especial o consecuencial, incluyendo a título enunciativo pero no limitativo cualquier pérdida de ganancias, de datos o de oportunidades de negocio, errores de software, tengan o no carácter previsible y que resulten o tengan conexión directa o indirecta con el uso de la Plataforma.</p>

<p>6.3. Finguer no se responsabiliza de cualquier pérdida o daño que pueda sufrir el Usuario como consecuencia del uso inadecuado de la Plataforma o si el Usuario incumple con los Términos y Condiciones de la Web o con las instruc- ciones que Finguer haya facilitado al usuario a través de cualquier canal de comunicación dispuesto al efecto. Asimis- mo, Finguer no será responsable por cualquier pérdida o daño que pueda sufrir el Usuario como consecuencia de la información facilitada directamente por el Propietario del parking en relación a cualquier aumento, cambio o modifi- cación de tarifas, horarios de apertura y cierre y demás restricciones que afecten al uso de las plazas de parking de su propiedad y que sean publicadas en la plataforma Web de Finguer.</p>

<p>6.4. Bajo ninguna circunstancia Finguer se hará responsable por multas, avisos de penalización de cualquier tipo derivados de la inobservancia por parte del Usuario de las normas del parking. Especialmente, ni Finguer ni el parking incurrirán en ningún tipo de responsabilidad resultado de incidentes (robos, daños en propiedad propia o ajena, fallos o desperfectos en los vehículos etc.) ya sea que tengan lugar dentro del parking, en los accesos y/o en las intermedia- ciones del parking o en su trayecto al mismo y/o que deriven o puedan derivar en delitos en los que el Usuario incurra o reciba. El Usuario será el único responsable de ponerse en contacto con las autoridades competentes y de resolver</p>

<p>cualquier cuestión que afecte a sus intereses o propiedades. En cualquier caso, el Usuario reconoce y acepta que Finguer puede poner a disposición de las autoridades pertinentes, todo o parte de su información personal, si así es requerido legalmente.</p>
<h3><strong>7. Propiedad Intelectual</strong></h3>
<p>7.1 Finguer es el legítimo propietario de la totalidad de los derechos, títulos e intereses de y asociados a la Platafor- ma Web, sus contenidos y aplicaciones informáticas, en su caso, incluyendo cualquier modificación, actualización y nuevas versiones así como cualquier marca, nombre comercial, know how, derechos de autor y cualquier otro derecho de propiedad industrial o intelectual inherente.</p>
<h3><strong>8. Política de Privacidad, Protección de Datos y Política de Cookies</strong></h3>
<p>8.1 A la aceptación de los presentes Términos y Condiciones de Uso, el Usuario reconoce y acepta haber leído, comprendido y aceptado nuestra Política de Privacidad, Protección de Datos y Política de Cookies.</p>
<h3><strong>9. Ley Aplicable y Jurisdicción</strong></h3>
<p>9.1 La interpretación y aplicación de los términos y condiciones de uso de la Plataforma se regirán por la Legisla- ción Española. Para la resolución de cualquier discrepancia que pudiera surgir en la interpretación y/o ejecución de los Términos y Condiciones de Uso aquí previstos, las partes se someten a la jurisdicción y competencia de los Tribunales de Barcelona.No obstante, en el caso de que la Legislación Española o Autonómica para la Defensa de Consumidores y Usuarios establezca la posibilidad de que el Usuario elija el fuero correspondiente a su lugar de residencia, se procede- rá conforme a lo dispuesto en dicha normativa.</p>

<h3><strong>10. Contacto</strong></h3>
<p>Para cualquier pregunta relacionada con los servicios de nuestra Plataforma Web y de los Términos y Condiciones que la regulan, puedes ponerte en contacto directamente en hello@finguer.com y mediante petición escrita dirigida a nuestra oficina:</p>

<p>BCN PARKING S.L</p>
<p>Carrer de l'Alt Camp, 9, 08830 Sant Boi de Llobregat, Barcelona</p>

</div>

<?php
// Footer
require_once(APP_ROOT . '/public/footer_html.php');